name: fl_umeng_link
description: Umeng link plugin for flutter, only Android and IOS are supported
version: 0.1.1
repository: https://github.com/Wayaer/fl_umeng_link.git

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  fl_umeng: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:

  plugin:
    platforms:
      android:
        package: fl.umeng.link
        pluginClass: UMengLinkPlugin
      ios:
        pluginClass: UMengLinkPlugin
